apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
      - name: netflix-app
        image: walaahij/netflix:latest
        ports:
        - containerPort: 80
        # Add this to enable Nginx metrics
        - containerPort: 8080
        env:
        - name: NGINX_STATUS_PORT
          value: "8080"
        
      # Add exporter sidecar
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        ports:
        - containerPort: 9113
        args:
          - "-nginx.scrape-uri=http://localhost:8080/stub_status"