apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix-app
          image: walaahij/netflix:latest
          ports:
            - containerPort: 80

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - '--nginx.scrape-uri=$(NGINX_STATUS_URL)'
          ports:
            - containerPort: 9111
          env:
            - name: NGINX_STATUS_URL
              value: http://127.0.0.1/stub_status
