apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  progressDeadlineSeconds: 600  # Increase timeout to 10 minutes
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: walaahij/netflix:latest
        ports:
        - containerPort: 80
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /  # Or your health check endpoint
            port: 80
          initialDelaySeconds: 30  # Increase for slow-starting apps
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /  # Or your health check endpoint
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 10