apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: walaahij/netflix:latest
        ports:
          - name: metrics  # Required for ServiceMonitor
            containerPort: 3000
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics