apiVersion: v1
kind: service
metadata:
  name: netflix-app
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: metrics
      port : 9111
      targetPort: 9111
      nodePort: 30008