apiVersion: v1
kind: Service
metadata:
  name: netflix-app
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 30008