apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9111"
spec:
  type: NodePort
  selector:
    app: netflix-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: metrics
      port: 9111
      targetPort: 9111
      nodePort: 30008