# netflix-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  namespace: netflix  # Important: specify namespace
  labels:
    app: netflix-app
    release: prometheus  # Needed for discovery
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30007
  - name: metrics  # Add dedicated metrics port
    port: 3000
    targetPort: 3000
  selector:
    app: netflix-app


# apiVersion: v1
# kind: Service
# metadata:
#   name: netflix-app
#   labels:
#     app: netflix-app
# spec:
#   type: NodePort
#   selector:
#     app: netflix-app
#   ports:
#     - port: 80              # The port exposed inside the cluster
#       targetPort: 3000      # Port inside the container
#       nodePort: 30007       # External port exposed on the node (EC2 VM)
